#   _____                     _ _                _____ _       __          __
#  / ____|                   | (_)              / ____| |      \ \        / /
# | |  __ _   _  __ _ _ __ __| |_  __ _ _ __   | (___ | | ___   \ \  /\  / /_ _ _ __ ___
# | | |_ | | | |/ _` | '__/ _` | |/ _` | '_ \   \___ \| |/ / | | \ \/  \/ / _` | '__/ __|
# | |__| | |_| | (_| | | | (_| | | (_| | | | |  ____) |   <| |_| |\  /\  / (_| | |  \__ \
#  \_____|\__,_|\__,_|_|  \__,_|_|\__,_|_| |_| |_____/|_|\_\\__, | \/  \/ \__,_|_|  |___/
#                                                            __/ |
#                                                           |___/
# Created by Darkness Development
# Version: 1.0.0-SNAPSHOT
# Compatibility: 1.8.X-1.16.X
settings:
  # Default Kit ID for all modes
  defaultKitID: 0
  # Toggle Plugin Hooks
  hooks:
    # SlimeWorldManager Link: https://www.spigotmc.org/resources/69974/
    SlimeWorldManager: true
    # PlaceholderAPI Link: https://www.spigotmc.org/resources/6245/
    PlaceholderAPI: true
  # GameStatus Color & Text Modifier
  status:
    waiting: '&a&lWaiting'
    starting: '&e&lStarting'
    playing: '&c&lPlaying'
    restarting: '&b&lRestarting'
  # Custom Names of GameStatus
  names:
    waiting: Waiting
    starting: Starting
    playing: Playing
    restarting: Restarting
  # Slime World Manager Setup | (Only if you have enabled your SlimeWorldManager Hook)
  SlimeWorldManager:
    # Load Types: MYSQL,MONGODB,FILE
    loadType: 'FILE'

